server:
  port: 8802
spring:
  application:
    name: config-stream-consumer
  cloud:
    #stream配置
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用来binding的整合
          type: rabbit #消息组件的类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              #RabbitMQ的相关配置
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #z这个名字是通道的名字
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json  #设置消息的类型本次为json文本则为text/plain
          binder: defaultRabbit  #设置要绑定的消息服务的具体设置
          group: atspringA

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2  #设置心跳时间默认30秒
    lease-expiration-duration-in-seconds: 5 #超时间隔默认90秒
    instance-id: receive-8802.com  #在信息列表显示主机名称
    prefer-ip-address: true #访问路径变为IP地址